#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : noto-emoji
Version  : 2017.03.10.color.emoji.ary.1
Release  : 2
URL      : http://localhost/cgit/projects/noto-emoji/snapshot/noto-emoji-2017-03-10-color-emoji-binary-1.tar.bz2
Source0  : http://localhost/cgit/projects/noto-emoji/snapshot/noto-emoji-2017-03-10-color-emoji-binary-1.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : OFL-1.1
Requires: noto-emoji-data

%description
No detailed description available

%package data
Summary: data components for the noto-emoji package.
Group: Data

%description data
data components for the noto-emoji package.


%prep
%setup -q -n noto-emoji-2017-03-10-color-emoji-binary-1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510693553
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1510693553
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/fonts/noto-emoji/NotoColorEmoji.ttf
/usr/share/fonts/noto-emoji/NotoEmoji-Regular.ttf
